### ISSUE TITLE
tortoise data update

### ISSUE THREAD

**Issue by blacksquirrelsyracuse** [hamishgibbs/espanola_tortoise_release#20]
not sure why by deleting data files and uploading new ones not possible.  I sent the new bulk data download standard format and name to your gmail.  this would streamline things alot.  thanks.

**Comment by hamishgibbs** [comment]
The website has been updated to accommodate the new format of the data.

Now, the site will be generated from a single file stored at `data/tortoise_locations_latest.xls`.

This is now tied in with the scheduled build job so the site will look for new data and try to rebuild itself daily. 

To update the site data, simply replace the data file with the new version of the file.

There is no need to preprocess the data or convert to a `.csv` file. This is handled in `preprocess_data.R`.

**Comment by hamishgibbs** [comment]
@blacksquirrelsyracuse we will check that the automated build works tomorrow. I will close this issue for now.
