### ISSUE TITLE
Collaborator images

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/espanola_tortoise_release#4]
Horizontal arrangement of images linked to collaborator homepages.

I can provide a GTRI logo, GC logos and DPNG logos on web. - @blacksquirrelsyracuse

**Comment by blacksquirrelsyracuse** [comment]
![GTRI logo](https://user-images.githubusercontent.com/59319264/84578815-97b2d280-ad96-11ea-8fe3-ad27bbccb409.jpg)

**Comment by blacksquirrelsyracuse** [comment]
![Slide2](https://user-images.githubusercontent.com/59319264/84578885-32131600-ad97-11ea-80c9-2b1be3e227d9.JPG)

**Comment by blacksquirrelsyracuse** [comment]
![Slide3](https://user-images.githubusercontent.com/59319264/84578890-393a2400-ad97-11ea-9cb8-37bdda76deea.JPG)

**Comment by hamishgibbs** [comment]
Done.
