### ISSUE TITLE
Just FYI uploaded to Data folder all tortoises all dates to 10 PM June 15 as one CSV

### ISSUE THREAD

**Issue by blacksquirrelsyracuse** [hamishgibbs/espanola_tortoise_release#9]

**Comment by hamishgibbs** [comment]
Thank, just updated. Still need to wait a little to get all tortoises with unique points on española - some are staying where they are and not forming valid lines. Also, I have thresholded dates > 2020-06-15 but some of the journey is still present - tomorrow we are remove the whole thing and get this thing running automatically.

**Comment by hamishgibbs** [comment]
Also, when uploading data could you put it in `espanola_tortoise_release/data` rather than `espanola_tortoise_release/docs/data`? The `docs` folder is a clone of all non `R` files in the repository that is generated when the website is built. Thanks!

**Comment by hamishgibbs** [comment]
All sorted.
